nome = str(input('Digite seu nome: ')).strip()
print('Muito prazer em te conhecer!')
print(nome.upper())
print(nome.lower())
print(len(nome.replace(' ', '')))
n = nome.split()
print('Seu primeiro nome é {}.'.format(n[0]))
print('Seu último nome é {}.'.format(n[len(n)-1]))
